### ISSUE TITLE
How do you add the Rezscore URL for the job posts?

### ISSUE THREAD

**Issue by taariq** [zcor/githubjobs#2]
Need some instructions on how to do that so we can link to the job.

**Comment by zcor** [comment]
🤔We can probably set this up to do it automatically

**Comment by taariq** [comment]
FYI: My post https://github.com/zcor/githubjobs/blob/master/sfbay/O(1)%20Labs%20--%20Product%20Manager.txt doesn't have a Rezscore link.

**Comment by taariq** [comment]
Still not clear how  **https://website.for.application/ bounty: INTEGER** is supposed to work @zcor

**Comment by zcor** [comment]
We updated the README file to make this easier.

**Comment by taariq** [comment]
awesome!
